### ISSUE TITLE
c3po messages in the minibuffer is noisy

### ISSUE THREAD

**Issue by skybert** [d1egoaz/c3po.el#1]
Hi, 

thanks for creating `c3po.el`, I've started to play with it, and find it useful.

One early comment from me, is that it's rather noisy that `c3po.el` writes its output to the minibuffer. The text is already in the `* *🤖C3PO🤖*` buffer and duplicating that in the minibuffer is just noise IMHO and it [looks like it was just meant for debugging?](https://github.com/d1egoaz/c3po.el/blob/main/c3po.el#L93)

Keep up the good work,

-Torstein 
PS: I wrote this message all by myself, with no robot assistance. Speling and grammar mistakes all belong to me :muscle:

**Comment by d1egoaz** [comment]
Done! Thanks for the reminder. That was indeed only intended for debugging.

fixed by:
https://github.com/d1egoaz/c3po.el/commit/dabfd86165a00516faa1a65e561b5aee01ff6c5f
